<?php

return [
	'HESABE_VERSION' => env('HESABE_VERSION'),
	'PAYMENT_API_URL' => env('PAYMENT_API_URL'),
	'MERCHANT_SECRET_KEY' => env('MERCHANT_SECRET_KEY'),
	'MERCHANT_IV' => env('MERCHANT_IV'),
	'ACCESS_CODE' => env('ACCESS_CODE'),
	'MERCHANT_CODE' => env('MERCHANT_CODE'),
	'SUCCESS_CODE' => env('SUCCESS_CODE'),
	'AUTHENTICATION_FAILED_CODE' => env('AUTHENTICATION_FAILED_CODE'),
];
